default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pai
  password: tigers
  host: db

development:
  <<: *default
  database: pai_pad_dev

test:
  <<: *default
  database: pai_pad_test

production:
  <<: *default
  database: pai_pad_production
  username: pai_pad
  password: <%= ENV["PAI_PAD_DATABASE_PASSWORD"] %>
